"use strict";

const minio = require("./minio");

/**
 * Returns metrics object name
 *
 * @returns
 */
function getObjectName() {
  const name = `${process.env.METRICS_NAME || "metrics.json"}`;
  return name;
}

/**
 * Get metrics. Object metrics is generated by the training phase (optional)
 *
 * @param {*} id Model unique id
 *
 * @return
 */
 async function get(id) {
  const exists = await minio.objectExists(id,  getObjectName());
  if (exists) {
    const metrics = await minio.getJsonObject(id, getObjectName());
    return metrics;
  }
  return {};
}

module.exports = {
  get,
}